# Generated by Django 2.1.4 on 2018-12-20 20:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='No UUID', help_text='Media universal unique identifier', max_length=36, verbose_name='uuid')),
                ('name', models.CharField(default='No title', help_text='Media name', max_length=100, verbose_name='name')),
                ('media_file', models.FileField(blank=True, upload_to=media.models.media_file_name)),
                ('url', models.URLField(editable=False, verbose_name='URL')),
                ('date', models.DateTimeField(help_text='Media creation date', verbose_name='date')),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 12, 20, 20, 8, 9, 677559), help_text='Last change', verbose_name='last modified')),
                ('note', models.TextField(blank=True, help_text='Note.. use as you wish!', max_length=300, verbose_name='note')),
                ('type', models.CharField(blank=True, choices=[('audio', 'audio'), ('imagem', 'imagem'), ('video', 'video'), ('arquivo', 'arquivo')], default='arquivo', help_text='Type of the media, like image, document, video, ...', max_length=14, verbose_name='type')),
                ('format', models.CharField(blank=True, choices=[('ogg', 'ogg'), ('ogv', 'ogv'), ('webm', 'webm'), ('mp4', 'mp4'), ('mp3', 'mp3'), ('jpg', 'jpg'), ('png', 'png'), ('pdf', 'pdf'), ('gif', 'gif'), ('odp', 'odp'), ('odt', 'odt'), ('oga', 'oga'), ('jpeg', 'jpeg')], default='ogg', help_text='Format of the media, like ogg, jpg, pdf, ...', max_length=14, verbose_name='format')),
                ('license', models.CharField(blank=True, help_text='License of the media, like, cc, gpl, bsd, ...', max_length=100, verbose_name='license')),
                ('is_local', models.BooleanField(default=False, help_text='True if media content is available locally', verbose_name='is local')),
                ('is_requested', models.BooleanField(default=False, help_text='True if media content is awaiting a local copy', verbose_name='is requested')),
                ('request_code', models.CharField(blank=True, editable=False, max_length=100)),
                ('num_copies', models.IntegerField(blank=True, default=1, help_text='Number of copies of the media in the repository', verbose_name='number of copies')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
