# Generated by Django 2.1.4 on 2018-12-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mocambos', 'mocambos')], help_text='Repository name taken from available repositories', max_length=60, verbose_name='name')),
                ('note', models.TextField(blank=True, help_text='Note.. use as you wish!', max_length=300, verbose_name='notes')),
                ('enable_sync', models.BooleanField(help_text='Tick here to enablesyncronization of this repository', verbose_name='synchronize')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
                'ordering': ('name',),
            },
        ),
    ]
