# Generated by Django 2.1.4 on 2018-12-20 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocambola', '0001_initial'),
        ('repository', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mucua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(editable=False, max_length=100)),
                ('note', models.TextField(blank=True, max_length=300)),
                ('uuid', models.CharField(choices=[('00000000-0000-0000-0000-000000000002', 'bittorrent'), ('f84a1327-febb-4199-a106-9c3fd2288826', 'dpadua'), ('f95720ce-a348-4211-90a6-2cb1f4c124d3', 'oxala'), ('00000000-0000-0000-0000-000000000001', 'web')], default='dandara', max_length=36, verbose_name='Mucua')),
                ('uri_backend', models.CharField(blank=True, default='', max_length=2048, verbose_name='Remote access to mucua')),
                ('mocambolas', models.ManyToManyField(through='mocambola.Mocambola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('weight', models.CharField(default='100', max_length=100)),
                ('mucua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_mucuas', to='mucua.Mucua')),
                ('mucuia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_mucuias', to='mucua.Mucua')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.AddField(
            model_name='mucua',
            name='mucuas',
            field=models.ManyToManyField(related_name='linked_mucuas', through='mucua.Rota', to='mucua.Mucua'),
        ),
        migrations.AddField(
            model_name='mucua',
            name='repository',
            field=models.ManyToManyField(to='repository.Repository'),
        ),
    ]
